library(stringr)
source("getSessionFeaturesTrimmed.R")
source("getfeaturesTrimmed.r")
source("processHead.R")
source("processProsody.r")
source("resampleTo.r")
source("resample.r")
source("getStartEndSilence.R")
source("processPhonemes.r")
improMFeaturesTrimmed<-list()
improFFeaturesTrimmed<-list()
scriptMFeaturesTrimmed<-list()
scriptFFeaturesTrimmed<-list()
for (i in 1:5){
  dir <- paste0("../corpus/IEMOCAP_full_release/Session",i,"/sentences/")
  improMFeaturesTrimmed[[i]] <- getSessionFeaturesTrimmed(dir,"M","impro")
  improFFeaturesTrimmed[[i]] <- getSessionFeaturesTrimmed(dir,"F","impro")
  scriptMFeaturesTrimmed[[i]] <- getSessionFeaturesTrimmed(dir,"M","script")
  scriptFFeaturesTrimmed[[i]] <- getSessionFeaturesTrimmed(dir,"F","script")
  write.table(improMFeaturesTrimmed[[i]], file=paste0("improMFeaturesTrimmed",i,".csv"),sep=",",row.names=FALSE)
  write.table(improFFeaturesTrimmed[[i]], file=paste0("improFFeaturesTrimmed",i,".csv"),sep=",",row.names=FALSE)
  write.table(scriptMFeaturesTrimmed[[i]], file=paste0("scriptMFeaturesTrimmed",i,".csv"),sep=",",row.names=FALSE)
  write.table(scriptFFeaturesTrimmed[[i]], file=paste0("scriptFFeaturesTrimmed",i,".csv"),sep=",",row.names=FALSE)
  saveRDS(improMFeaturesTrimmed[[i]], file = paste0("improMFeaturesTrimmed",i,".rda"))
  saveRDS(improFFeaturesTrimmed[[i]], file = paste0("improFFeaturesTrimmed",i,".rda"))
  saveRDS(scriptMFeaturesTrimmed[[i]], file = paste0("scriptMFeaturesTrimmed",i,".rda"))
  saveRDS(scriptFFeaturesTrimmed[[i]], file = paste0("scriptFFeaturesTrimmed",i,".rda"))  
}